### ISSUE TITLE
[Feature]记事本建议

### ISSUE THREAD

**Issue by DUKISS** [qd-today/qd#154]
王哥，一个账号可不可以设定多个记事本(不需要再额外注册账号那种)，记事本要是能自定义名字就更好了。这样的话就可以用记事本做不同网站的回复库了，到时候就可以不仅签到，还可以自动回复了

**Comment by a76yyyy** [comment]
一个用户目前只建立一个记事本，需要使用多个记事本可以使用多个账号
该需求优先级较低，不过可以考虑加入该需求

**Comment by loveqianool** [comment]
请问记事本这个功能是在什么情况下会使用到呢？我一直不明白有什么用处，所以也一直没使用上。

**Comment by mysharebob** [comment]
大佬好，记事本1个的确不太方便，虽然可以注册其他账号，但是管理不方便。
关键是我还不会用记事本。我想把记事本用于记录页面ID，新的页面ID与记事本中的老ID对比，做一个IF判断，但是不知道怎么读取记事本的变量名和数组名，或者语法是什么，怎么判断，大佬有没有教程啥的。

**Comment by mysharebob** [comment]
对了，记事本还没有删除的功能。我会attend和read，但不知道变量名，不会做If 判断。

**Comment by DUKISS** [comment]
记事本只能使用多账号的问题，只能继续给王哥提交Issue了，我提交了但是王哥认为需求不大，人多了也许会解决。
框架好像不支持IF语句，可以暂时放弃了，或者另辟蹊径。记事本里记录id做对比的情况亦如此。另外不知道你具体情况也没法给出其他建议，当然知道了可能也给不了其他建议，因为我也只是刚入了门的菜鸟[捂脸]。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 凌晨0:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154)




 
大佬好，记事本1个的确不太方便，虽然可以注册其他账号，但是管理不方便。
 关键是我还不会用记事本。我想把记事本用于记录页面ID，新的页面ID与记事本中的老ID对比，做一个IF判断，但是不知道怎么读取记事本的变量名和数组名，或者语法是什么，怎么判断，大佬有没有教程啥的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DUKISS** [comment]
这个问题我也跟王哥说过，他说可以自己抓包框架删除记事本的操作，把获取的请求用做API用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 凌晨0:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154)




 
对了，记事本还没有删除的功能。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loveqianool** [comment]
记事本可以用 workers kv 替代
https://api.cloudflare.com/#workers-kv-namespace-properties
https://github.com/tuhinpal/CloudflareDB

**Comment by mysharebob** [comment]
一些需求就是，定期刷新一些新帖或文章，如果有新文章，就钉钉推送。比如PT站开放注册。所以需要文章ID进行对比是否为新。看来等框架得许久了。干脆用python自己写几行代码吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 上午7:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154)




 记事本只能使用多账号的问题，只能继续给王哥提交Issue了，我提交了但是王哥认为需求不大，人多了也许会解决。 
 框架好像不支持IF语句，可以暂时放弃了，或者另辟蹊径。记事本里记录id做对比的情况亦如此。另外不知道你具体情况也没法给出其他建议，当然知道了可能也给不了其他建议，因为我也只是刚入了门的菜鸟[捂脸]。 
 
 
 
 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年2月8日(周二) 凌晨0:03 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154) 
 
 
 
 
   
 大佬好，记事本1个的确不太方便，虽然可以注册其他账号，但是管理不方便。 
  关键是我还不会用记事本。我想把记事本用于记录页面ID，新的页面ID与记事本中的老ID对比，做一个IF判断，但是不知道怎么读取记事本的变量名和数组名，或者语法是什么，怎么判断，大佬有没有教程啥的。 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loveqianool** [comment]
> 一些需求就是，定期刷新一些新帖或文章，如果有新文章，就钉钉推送。比如PT站开放注册。所以需要文章ID进行对比是否为新。看来等框架得许久了。干脆用python自己写几行代码吧。

比较文章 id 可以用 {{ liu|int == er|int }} 比较两个对象相等 返回True、False 返回:False
看这里 https://www.quchao.net/QianDaoEXP.html

------
试了下能匹配数字，字符串好像不行。

**Comment by DUKISS** [comment]
大佬的网站我看过，获益匪浅。只不过有些东西没到用的时候想不起来，哈哈。==判断有没有新帖如果不能用于数组感觉亦有局限，能用于数组了才会方便些。我没有这方面的尝试，没研究过，回头好好看一下。多谢告知！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 凌晨3:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154)




  
一些需求就是，定期刷新一些新帖或文章，如果有新文章，就钉钉推送。比如PT站开放注册。所以需要文章ID进行对比是否为新。看来等框架得许久了。干脆用python自己写几行代码吧。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月8日(周二) 上午7:52 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154) 记事本只能使用多账号的问题，只能继续给王哥提交Issue了，我提交了但是王哥认为需求不大，人多了也许会解决。 框架好像不支持IF语句，可以暂时放弃了，或者另辟蹊径。记事本里记录id做对比的情况亦如此。另外不知道你具体情况也没法给出其他建议，当然知道了可能也给不了其他建议，因为我也只是刚入了门的菜鸟[捂脸]。
 ---原始邮件--- 发件人: @.&amp;gt; 发送时间: 2022年2月8日(周二) 凌晨0:03 收件人: @.&amp;gt;; 抄送: @.@.&amp;gt;; 主题: Re: [qiandao-today/qiandao] [Feature]记事本建议 (Issue #154) 大佬好，记事本1个的确不太方便，虽然可以注册其他账号，但是管理不方便。 关键是我还不会用记事本。我想把记事本用于记录页面ID，新的页面ID与记事本中的老ID对比，做一个IF判断，但是不知道怎么读取记事本的变量名和数组名，或者语法是什么，怎么判断，大佬有没有教程啥的。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.&gt;
  
比较文章 id 可以用 {{ liu|int == er|int }} 比较两个对象相等 返回True、False 返回:False
 看这里，他写的文档，直观多了 https://www.quchao.net/QianDaoEXP.html
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by a76yyyy** [comment]
目前只支持使用 `id` 新建删除多记事本, 暂不支持给定记事本 `title`
