### ISSUE TITLE
[Bug] 公共模板第三方库添加失败

### ISSUE THREAD

**Issue by qhq** [qd-today/qd#183]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20211228

### Bug on OS

Windows

### Bug on Platform

Docker/Linux 64位

### To Reproduce

公共模板中添加第三方库
https://github.com/lksky8/sign-har
刷新后，下方列表中无库内模板

### Describe the Bug

公共模板中添加第三方库
https://github.com/lksky8/sign-har
刷新后，下方列表中无库内模板

### QianDao log

```shell
无
```

### Expected behavior

无

**Comment by acooler15** [comment]
缺少一个json文件，请对比官方库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月2日(周日) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiandao-today/qiandao] [Bug] 公共模板第三方库添加失败 (Issue #183)




 
Verify steps
  
 Tracker 我已经在 Issue Tracker 中找过我要提出的问题 

 Latest 我已经使用 最新源码 测试过，问题依旧存在 

 Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题 

 Meaningful 我提交的不是无意义的 催促更新或修复 请求 
 
QianDao Version
 
20211228
 
Bug on OS
 
Windows
 
Bug on Platform
 
Docker/Linux 64位
 
To Reproduce
 
公共模板中添加第三方库
 https://github.com/lksky8/sign-har
 刷新后，下方列表中无库内模板
 
Describe the Bug
 
公共模板中添加第三方库
 https://github.com/lksky8/sign-har
 刷新后，下方列表中无库内模板
 
QianDao config
 
No response
 
QianDao log
 无
 
Expected behavior
 
无
 
Screenshots
 
No response

**Comment by qhq** [comment]
谢谢，没留意har中间夹了一个json文件 😄
