### ISSUE TITLE
[Bug] POST请求中body的内容无法保存

### ISSUE THREAD

**Issue by DUKISS** [qd-today/qd#260]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220208

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

无

### Describe the Bug

最近需要修改某个模板的POST请求body内容时发现无法保存成功，修改后保存时没有提示任何异常，但是保存完后再打开模板会发现没有保存，还是之前的数据。起初以为是更新版本后的原因，结果发现0208包括之后的版本都有这个现象。再之前的版本没测试，不知道是否也这样。

### QianDao log

```shell
无
```

### Expected behavior

修复即可

**Comment by acooler15** [comment]
麻烦提供下这个请求的截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 上午8:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiandao-today/qiandao] [Bug] POST请求中body的内容无法保存 (Issue #260)




 
Verify steps
  
 Tracker 我已经在 Issue Tracker 中找过我要提出的问题 

 Latest 我已经使用 最新源码 测试过，问题依旧存在 

 Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题 

 Meaningful 我提交的不是无意义的 催促更新或修复 请求 
 
QianDao Version
 
20220208
 
Bug on OS
 
Linux
 
Bug on Platform
 
Docker/Linux 64位
 
To Reproduce
 
无
 
Describe the Bug
 
最近需要修改某个模板的POST请求body内容时发现无法保存成功，修改后保存时没有提示任何异常，但是保存完后再打开模板会发现没有保存，还是之前的数据。起初以为是更新版本后的原因，结果发现0208包括之后的版本都有这个现象。再之前的版本没测试，不知道是否也这样。
 
QianDao config
 
No response
 
QianDao log
 无
 
Expected behavior
 
修复即可
 
Screenshots
 
No response

**Comment by DUKISS** [comment]
![Uploading IMG_20220512_082552.jpg…]()

**Comment by DUKISS** [comment]
![Uploading IMG_20220512_083317.jpg…]()

**Comment by a76yyyy** [comment]
> Uploading IMG_20220512_083317.jpg…

请等待图片上传完成后再点击评论按钮

最好将har文件压缩为zip文件之后上传至此issue

**Comment by DUKISS** [comment]
![IMG_20220512_083317](https://user-images.githubusercontent.com/39652212/168207156-417b9e8a-90a9-4b4e-a6e8-4d4ea5961116.jpg)

**Comment by DUKISS** [comment]
下面文本框这一部分

**Comment by acooler15** [comment]
我没能复原该情况😅，可以的话，在电脑上查看浏览器控制台保存时有没有报错，查看签到后台有没有报错。

**Comment by DUKISS** [comment]
已经发给王哥了一份，模板第15条的Request Payload保存不上

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiandao-today/qiandao] [Bug] POST请求中body的内容无法保存 (Issue #260)




 
我没能复原该情况😅，可以的话，在电脑上查看浏览器控制台保存时有没有报错，查看签到后台有没有报错。

**Comment by a76yyyy** [comment]
暂时无法复现, 等待后续能够复现的时候再打开这一issue
